ffmpeg: Fix the HAVE_LIBAVCODEC_CONST_AVCODEC test
The test was not pulling in the FFmpeg header or library paths.

/home/brad/ports/pobj/ppsspp-1.17.1/bin/c++ -DHAVE_LIBAVCODEC_CONST_AVCODEC  -O2 -pipe -g -pedantic -Wall -Werror -Wno-unused-variable
-std=gnu++17 -MD -MT CMakeFiles/cmTC_9e9ce.dir/src.cxx.o -MF CMakeFiles/cmTC_9e9ce.dir/src.cxx.o.d -o CMakeFiles/cmTC_9e9ce.dir/src.cxx.o
-c /home/brad/ports/pobj/ppsspp-1.17.1/build-aarch64/CMakeFiles/CMakeScratch/TryCompile-E3C4ib/src.cxx
/home/brad/ports/pobj/ppsspp-1.17.1/build-aarch64/CMakeFiles/CMakeScratch/TryCompile-E3C4ib/src.cxx:2:12: fatal error:
'libavcodec/avcodec.h' file not found
                #include <libavcodec/avcodec.h>
                          ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Fixing just the header path.

/home/brad/ports/pobj/ppsspp-1.17.1/bin/c++ -O2 -pipe -g -pedantic -Wall -Werror -Wno-unused-variable CMakeFiles/cmTC_cf251.dir/src.cxx.o
-o cmTC_cf251  -lavcodec  -lavformat  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib && :
ld.lld: error: unable to find library -lavcodec
ld.lld: error: unable to find library -lavformat