Linux: ignore missing MAP_NORESERVE on FreeBSD
Common/MemArenaPosix.cpp:111:71: error: use of undeclared identifier 'MAP_NORESERVE'
        void *base = mmap(0, EIGHT_GIGS, PROT_NONE, MAP_ANON | MAP_PRIVATE | MAP_NORESERVE, -1, 0);
                                                                             ^